-- Leave a large ID space reserved for master-data and test-data
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1000000;

CREATE TABLE BINARYOBJECT (
  ID                  NUMBER(19),
  MODIFICATIONCOUNTER NUMBER(10, 0) NOT NULL,
  CONTENT             BLOB,
  FILESIZE            NUMBER(10, 0) NOT NULL,
  MIMETYPE            VARCHAR(255),
  CONSTRAINT PK_BINARYOBJECT_ID PRIMARY KEY (ID)
);

CREATE TABLE PROTOCOLENTRY (
  ID              NUMBER(19),
  MODIFICATIONCOUNTER NUMBER(10, 0) NOT NULL,  
  TIMESTAMP       TIMESTAMP NOT NULL,
  TEXT            VARCHAR(255),
  CONSTRAINT PK_PROTOCOL_ID PRIMARY KEY (ID)
);